(defun inspiration-648409 ()
  "Theme generated by Sweyla: http://inspiration.sweyla.com/code/seed/648409/"
  (interactive)
  (color-theme-install
   '(inspiration-648409
     ((background-color . "#0B0000")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#EA63CD"))))
     (font-lock-constant-face ((t (:foreground "#C694A0"))))
     (font-lock-builtin-face ((t (:foreground "#F79968"))))
     (font-lock-function-name-face ((t (:foreground "#FF9255"))))
     (font-lock-variable-name-face ((t (:foreground "#D7BFB2"))))
     (font-lock-keyword-face ((t (:foreground "#505852"))))
     (font-lock-string-face ((t (:foreground "#EE753B"))))
     (font-lock-doc-string-face ((t (:foreground "#EE753B"))))
     (font-lock-type-face ((t (:foreground "#DA1CF9"))))
     )))

(defun inspiration-990434 ()
  "Theme generated by Sweyla: http://inspiration.sweyla.com/code/seed/990434/"
  (interactive)
  (color-theme-install
   '(inspiration-990434
     ((background-color . "#000D03")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#C1E261"))))
     (font-lock-constant-face ((t (:foreground "#00ACE5"))))
     (font-lock-builtin-face ((t (:foreground "#00CBB5"))))
     (font-lock-function-name-face ((t (:foreground "#5FFF66"))))
     (font-lock-variable-name-face ((t (:foreground "#0BD81B"))))
     (font-lock-keyword-face ((t (:foreground "#7BCBC1"))))
     (font-lock-string-face ((t (:foreground "#00C8EC"))))
     (font-lock-doc-string-face ((t (:foreground "#00C8EC"))))
     (font-lock-type-face ((t (:foreground "#8CFF1F"))))
     )))

(defun inspiration-144382 ()
  "Theme generated by Sweyla: http://inspiration.sweyla.com/code/seed/144382/"
  (interactive)
  (color-theme-install
   '(inspiration-144382
     ((background-color . "#FAF6FA")
      (foreground-color . "#000000")
      (background-mode . bright)
      (border-color . "#C8C8C8")
      (cursor-color . "#000000")
      (mouse-color . "#C8C8C8"))
     (mode-line ((t (:foreground "#000000" :background "#C8C8C8"))))
     (region ((t (:background "#C8C8C8"))))

     (font-lock-comment-face ((t (:foreground "#001350"))))
     (font-lock-constant-face ((t (:foreground "#289C77"))))
     (font-lock-builtin-face ((t (:foreground "#2900BE"))))
     (font-lock-function-name-face ((t (:foreground "#DE00A9"))))
     (font-lock-variable-name-face ((t (:foreground "#4100B6"))))
     (font-lock-keyword-face ((t (:foreground "#7A2A97"))))
     (font-lock-string-face ((t (:foreground "#490032"))))
     (font-lock-doc-string-face ((t (:foreground "#490032"))))
     (font-lock-type-face ((t (:foreground "#000029"))))
     )))

(provide 'inspiration)
